In [31]:
import numpy as np

In [2]:
#Entradas X e Saída Y:

In [30]:
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

Y = np.array([[0],
              [1],
              [1],
              [0]])

In [40]:
#Parâmetros:

Learning_rate = 0.4
entrada = 2
saída = 1
camada_oculta = 3
epocas = 10000


In [ ]:
#Função de Ativação sigmóide:

In [34]:
def sigmoid(x):
  return 1/(1 + np.exp(-x))


In [ ]:
#Derivada da função sigmóide para cálculo do Delta:

In [35]:
def deriv_sigmoid(x):
  return x * (1 - x)

In [ ]:
#Função cálculo do erro:

In [36]:
def erro_saida(Y,output):
  return(Y - output)

In [69]:
#Criando matrizes com pesos aleatórios:
weight_input  = np.random.random(size=(entrada, camada_oculta))
weight_output = np.random.random(size=(camada_oculta, saída))

In [ ]:
#Feedforward e Backpropagation

In [70]:
for epoch in range(epocas):
 input_to_hidden = np.dot(X,weight_input)
 output_hidden = sigmoid(input_to_hidden)
 hidden_to_output = np.dot(output_hidden,weight_output)
 output = sigmoid(hidden_to_output)

#Cálculo do erro de saída e Delta de Saída:

 erro = erro_saida(Y,output)
 DeltaSaída = erro * deriv_sigmoid(output)

 #Cálculo erro e Delta da camada oculta:
 erro_oculta = np.dot(DeltaSaída,weight_output.T)
 DeltaOculta = erro_oculta * deriv_sigmoid(output_hidden)

#Atualizando os pesos entre a camada oculta e saída:
 weight_output = weight_output + np.dot(output_hidden.T,DeltaSaída) * Learning_rate

#Atualizando os pesos entre entrada e a camada oculta:
 weight_input = weight_input + np.dot(X.T,DeltaOculta) * Learning_rate





In [71]:
print(" Saída da rede neural após treinamento")
print(output)

print(" Predição")
predicao = np.round(output)
print(predicao)

print("Pesos da entrada para camada oculta")
print(weight_input)

print("Pesos da camada oculta para saída")
print(weight_output)

 Saída da rede neural após treinamento
[[0.0516567 ]
 [0.96798202]
 [0.96798384]
 [0.01320858]]
 Predição
[[0.]
 [1.]
 [1.]
 [0.]]
Pesos da entrada para camada oculta
[[ 5.31656523  6.09980855 -3.67785682]
 [ 5.32275809 -3.66086379  6.14460955]]
Pesos da camada oculta para saída
[[13.19803194]
 [-9.51142617]
 [-9.50691131]]
